Imagen
byte** Imagen::datos
int Imagen::filas
int Imagen::columnas
Imagen::Imagen()
Constructor por defecto de la clase imagen.
Imagen vacía, sin filas ni columnas
Imagen::Imagen(int fils, int cols)
Constructor de imagen con filas filas y columnas columnas.
fils Número de filas de la imagen cols Número de columnas de la imagen filas > 0 && columnas > 0 Imagen con valores basura, sin inicializar
Imagen::Imagen(const Imagen &otra)
Constructor de copia de la clase imagen.
otra Imagen que se quiere copiar La imagen será identica a otra
Imagen::~Imagen()
Destructor de la clase Imagen.
Imagen inutilizable salvo que sea "reinicializada"
Imagen & Imagen::operator=(const Imagen &otra)
Operador = de la clase imagen, que copia los datos de otra.
otra Imagen que se quiere copiar Referencia a un objeto Imagen
int Imagen::NumFilas() const
Devuelve el número de filas de la imagen.
Número de filas de la imagen
int Imagen::NumColumnas() const
Devuelve el número de columnas de la imagen.
Número de columnas de la imagen
void Imagen::LeerImagenPGM(const string nombre)
Lee una imagen PGM.
nombre Nombre del archivo de entrada
void Imagen::EscribirImagenPGM(const string nombre)
Guarda una imagen en formato PGM.
nombre Nombre del archivo de salida
byte Imagen::GetValor(int fil, int col) const
Consulta el valor de un píxel de la imagen.
fil Índice de la fila del píxel cuyo valor se quiere consultar col índice de la columna del píxel cuyo valor se quiere consultar 0 <= fil < NumFilas() && 0 <= col < NumColumnas() Valor de luminosidad del píxel especificado
Referenced by ExtraerSubimagen.
void Imagen::SetValor(int fil, int col, byte valor)
Modifica el valor de un píxel de la imagen.
fil Índice de la fila del píxel cuyo valor se quiere modificar col Índice de la columna del píxel cuyo valor se quiere modificar 0 <= fil < NumFilas() && 0 <= col < NumColumnas() && 0 <= valor <= 255
Referenced by ExtraerSubimagen.
void Imagen::InsertarFila(int pos)
Inserta una fila de píxeles vacíos en la posición indicada.
pos Índice en el que se insertará la fila de píxeles
References EcualizarFila.
Referenced by Interpolar.
void Imagen::InsertarColumna(int pos)
Inserta una columna de píxeles vacíos en la posición indicada.
pos Índice en el que se insertará la columna de píxeles
References EcualizarColumna.
Referenced by Interpolar.
void Imagen::Ecualizar(int valor)
Llena la imagen de píxeles de la luminosidad indicada.
valor Valor con el que se rellenará la imagen
void Imagen::EcualizarFila(int fil, int valor)
Llena una fila de píxeles con el valor indicado.
fil Índice de la fila a llenar valor Valor con el que se rellena la fila
Referenced by InsertarFila.
void Imagen::EcualizarColumna(int col, int valor)
Llena una columna de píxeles con el valor indicado.
fil Índice de la columna a llenar valor Valor con el que se rellena la columna
Referenced by InsertarColumna.
void Imagen::ExtraerSubimagen(const Imagen &otra, const int fil, const int col, const int fils_sub, const int cols_sub)
Extrae una subimagen PGM de otra imagen PGM.
otra Imagen de la que extraer la subimagen fil Índice de la fila a partir de la cual se creará la subimagen resultante col Índice de la columna a partir de la cual se creará la subimagen resultante fils_sub Tamaño vertical de la imagen resultado cols_sub Tamaño horizontal de la imagen resultado (fil + filas_sub) < fich_orig.NumFilas() && (col + filas_col) < fich_orig.NumColumnas() El contenido de la imagen se ve reescrito por el de la subimagen indicada de otra.
References GetValor, SetValor.
Referenced by HacerZoom.
void Imagen::HacerZoom(const Imagen &otra, const int fil, const int col, const int fils_sub, const int cols_sub)
Hace zoom a una imagen, esto es:
Extrae de ella una subimagen. Aplica a la subimagen una interpolacion consistente en añadir filas (y columnas) en las que el valor de cada píxel será una media de los valores de los píxeles que tenga arriba y abajo (a izquierda y derecha, respectivamente) fich_orig Nombre del fichero que contiene la imagen original fich_rdo Nombre del fichero que contendrá el resultado fil Fila a partir de la cual se creará la subimagen resultante col Columna a partir de la cual se creará la subimagen resultante fils_sub Tamaño vertical de la imagen resultado cols_sub Tamaño horizontal de la imagen resultado (fil + filas_sub) < fich_orig.NumFilas() && (col + filas_col) < fich_orig.NumColumnas()
References ExtraerSubimagen, Interpolar.
void Imagen::Interpolar()
Aplica a la subimagen una interpolacion consistente en añadir filas (y columnas) en las que el valor de cada píxel será una media de los valores de los píxeles que tenga arriba y abajo (a izquierda y derecha, respectivamente)
References InsertarColumna, InsertarFila.
Referenced by HacerZoom.
void Imagen::AumentarContraste(const int e1, const int e2, const int s1, const int s2)
Aumenta el contraste de una imagen mediante un estiramiento de su histograma.
fich_orig Nombre del fichero que contiene la imagen original fich_rdo Nombre del fichero que contendrá el resultado e1 Coordenada x del primer punto que transforma la gráfica de la e2 s1 s2 Si la operación ha tenido éxito
void Imagen::ReservarMemoria(int fils, int cols)
Reserva memoria para un dato de tipo Imagen.
fils Filas a reservar cols Columnas a reservar
void Imagen::LiberarMemoria()
Libera la memoria ocupada por un objeto de tipo Imagen.
void Imagen::CopiarDatos(const Imagen otra)
Copia los datos de otra imagen.
otra Imagen de la que se quieren copiar los datos
TipoImagen Imagen::LeerTipoImagen(ifstream &f)
Devuelve el tipo de imagen del archivo.
f Flujo a usar. Devuelve el tipo de la imagen en el archivo TipoImagen
TipoImagen Imagen::LeerTipoImagen(const char *nombre)
Devuelve el tipo de imagen del archivo.
nombre Devuelve el tipo de la imagen en el archivo TipoImagen
char Imagen::SaltarSeparadores(ifstream &f)
Permite saltar los separadores de un archivo PGM para leer seguidamente la imagen.
f Flujo a usar para leer los separadores char
bool Imagen::LeerCabecera(ifstream &f, int &fils, int &cols)
Lee la cabecera de un archivo PGM, que contiene entre otras cosas las dimensiones de la imagen.
f Flujo usado para leer la cabecera