.TH "imagen.cpp" 3 "Miércoles, 10 de Noviembre de 2021" "tdaImagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.cpp \- Fichero con definiciones para la manipulación de imágenes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'imagen\&.h'\fP
.br

.SH "Descripción detallada"
.PP 
Fichero con definiciones para la manipulación de imágenes\&. 

Permite la manipulación de archivos de tipo PGM\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para tdaImagen del código fuente\&.
