.TH "imagen.h" 3 "Miércoles, 10 de Noviembre de 2021" "tdaImagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.h \- Fichero cabecera para la manipulación de imágenes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBImagen\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBTipoImagen\fP { \fBIMG_DESCONOCIDO\fP, \fBIMG_PGM\fP }"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera para la manipulación de imágenes\&. 

Permite la manipulación de archivos de tipo PGM\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para tdaImagen del código fuente\&.
